// Generated by https://quicktype.io

export interface IPairOption {
    name:         string;
    pairSymbol:   string[];
    tokenAddress: string;
}

export interface IPair {[key: string]:IPairOption}